### ISSUE TITLE
Packing single precision floating point number

### ISSUE THREAD

**Issue by ghost** [msgpack/msgpack-haskell#37]
In the msgpack specification, prefix of "Float" type is 0xCA, but implementation of msgpack-haskell is 0xCB.

<pre><code>instance Packable Float where
  from f =
    fromWord8 0xCB <>
    fromWord32be (cast f)
</code></pre>

http://wiki.msgpack.org/display/MSGPACK/Format+specification#Formatspecification-float

**Comment by hvr** [comment]
resolved by d6509c0f1cb4e2904fe662bebf198ad76f151746
