### ISSUE TITLE
msgpack-0.7 with relaxed upper bounds

### ISSUE THREAD

**Issue by nh2** [msgpack/msgpack-haskell#57]
Hi,

I saw that you released msgpack-1.0 - congrats!

However, the changes are quite a lot (e.g. switching to `binary`).

Would you mind making another point release in the 0.7 series that allows higher upper bounds on some standard packages like `text,attoparsec,template-haskell`?

Currently I have to use `--allow-newer` to use it, see e.g. here: https://travis-ci.org/nh2/call-haskell-from-anything/jobs/61278874#L184

Thanks!

**Comment by hvr** [comment]
Is this still desired?

**Comment by nh2** [comment]
One moment, I will check

**Comment by nh2** [comment]
It looks like I have [switched my use cases](https://github.com/nh2/call-haskell-from-anything/commit/1f9500310bfbfdef17ec12a7b1e4ae7b5013d08b#diff-f0cb291169267712709d8d70cc989def) from https://hackage.haskell.org/package/msgpack to https://hackage.haskell.org/package/data-msgpack since (the latter was made "since the original author is unreachable").

So I personally would no longer need this, given that the other package also claims "This fork incorporates a number of bugfixes and is actively being developed".

**Comment by hvr** [comment]
Fair enough; just for the record, effective immediately this library is maintained again :-)

**Comment by nh2** [comment]
@hvr OK, good to know!

Have you already had a chance to look at the differences the fork has made so far, maybe some of them are useful to pick back up?

**Comment by hvr** [comment]
I skimmed the fork and I think most of the functional non-refactoring changes were already submitted as PRs to this repo (and have been merged). I'll take a closer look at some point in the future to see if there's anything else I'd like to steal back... :-)
