### ISSUE TITLE
Incorrect bounds

### ISSUE THREAD

**Issue by phadej** [msgpack/msgpack-haskell#63]
I have to make a revision on Hackage: https://hackage.haskell.org/package/msgpack-1.0.0/revisions/

As `msgpack-1.0.0` uses `OverloadedLists` the `base` have to be restricted to `>=4.7`.

Also I added an upper bound on `binary` as there was name resolution clash for i.e. `getInt8` on GHC8.0 build. Haven't investigated it further. I recommend adding upper bounds to all dependencies, it's much easier to relax them for most recent version, then try to restrict bounds afterwards.

**Comment by hvr** [comment]
This was addressed in db978e0b72b37fd5b9e3dbe38df6c9e7dea1def5
