### ISSUE TITLE
32 bit float encoding looks incorrect

### ISSUE THREAD

**Issue by hcarty** [msgpack/msgpack-haskell#66]
Based on https://github.com/msgpack/msgpack-haskell/blob/master/msgpack/src/Data/MessagePack/Put.hs#L61 which, as of this writing, puts `0xcb` rather that `0xca` as the tag for a 32 bit floating point value.

I'm not a user of the library, just noticed the discrepancy while looking at msgpack implementations.

**Comment by hvr** [comment]
fixed by d6509c0f1cb4e2904fe662bebf198ad76f151746
