### ISSUE TITLE
Hackage release does not compile

### ISSUE THREAD

**Issue by iphydf** [msgpack/msgpack-haskell#67]
A recent (-ish.. from 2015) commit fixed a compilation problem caused by missing Functor and DeriveDataTypable. Please create a new hackage release so I don't need to install from github.

**Comment by hvr** [comment]
This seems to have been solved long ago as https://matrix.hackage.haskell.org/package/msgpack-rpc shows that the current  msgpack-rpc-1.0.0 release compiles just fine with GHC 7.10.3 through GHC 8.6.5
