### ISSUE TITLE
Allow binary-0.8

### ISSUE THREAD

**Issue by jchia** [msgpack/msgpack-haskell#72]
With binary-0.8, compilation fails because of ambiguity for functions like getWord16be. This should be fixable by changing the import of Data.Binary.

**Comment by aloiscochard** [comment]
I think this project is dead, please see: https://github.com/TokTok/hs-msgpack

**Comment by jchia** [comment]
Well, until someone takes over the maintenance of the hackage package and fixes the issue, I'm just using my own fork.

**Comment by aloiscochard** [comment]
@jchia this precisely why I was pointing you to this maintained fork which have all fixes: http://hackage.haskell.org/package/data-msgpack

Not sure why you would prefer keeping your own fork?

**Comment by jchia** [comment]
Oh, I didn't realize it has been added to hackage. Thanks for pointing it out. I'll see if I can use that and if not I'll send my pull request.
