### ISSUE TITLE
Unable to build msgpack

### ISSUE THREAD

**Issue by timyounes** [msgpack/msgpack-haskell#75]
`D:\ALL_FILES\installers\HASKELL\msgpack-haskell-master\msgpack>runhaskell setup.
lhs build
Warning: If linking fails, consider installing KB2533623.
Building msgpack-1.0.0...
Preprocessing library msgpack-1.0.0...
[2 of 5] Compiling Data.MessagePack.Get ( src\Data\MessagePack\Get.hs, dist\buil
d\Data\MessagePack\Get.o )

src\Data\MessagePack\Get.hs:53:30: error:
    Ambiguous occurrence `getInt8'
    It could refer to either `Data.Binary.Get.getInt8',
                             imported from `Data.Binary.Get' at src\Data\Message
Pack\Get.hs:25:1-32
                          or `Data.MessagePack.Get.getInt8',
                             defined at src\Data\MessagePack\Get.hs:123:1

src\Data\MessagePack\Get.hs:54:30: error:
    Ambiguous occurrence `getInt16be'
    It could refer to either `Data.Binary.Get.getInt16be',
                             imported from `Data.Binary.Get' at src\Data\Message
Pack\Get.hs:25:1-32
                          or `Data.MessagePack.Get.getInt16be',
                             defined at src\Data\MessagePack\Get.hs:126:1

src\Data\MessagePack\Get.hs:55:30: error:
    Ambiguous occurrence `getInt32be'
    It could refer to either `Data.Binary.Get.getInt32be',
                             imported from `Data.Binary.Get' at src\Data\Message
Pack\Get.hs:25:1-32
                          or `Data.MessagePack.Get.getInt32be',
                             defined at src\Data\MessagePack\Get.hs:129:1

src\Data\MessagePack\Get.hs:56:30: error:
    Ambiguous occurrence `getInt64be'
    It could refer to either `Data.Binary.Get.getInt64be',
                             imported from `Data.Binary.Get' at src\Data\Message
Pack\Get.hs:25:1-32
                          or `Data.MessagePack.Get.getInt64be',
                             defined at src\Data\MessagePack\Get.hs:132:1

D:\ALL_FILES\installers\HASKELL\msgpack-haskell-master\msgpack>`

**Comment by hvr** [comment]
This should have been resolved by the latest release http://hackage.haskell.org/package/msgpack-1.0.1.0
